version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwd:/mosquitto/passwd
      - ./mosquitto/certs:/mosquitto/certs

  mqtt-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - mosquitto

